spring:
  application:
    name: bigdata
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://120.24.25.238/uma?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root


mybatis:
  mapper-locations: classpath:sqlmap/*.xml
